WebsiteThietBiDienTu/Models/Pager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebsiteThietBiDienTu.Models
{
    public class Pager
    {
        public int TotalItems { get; set; }
        public int CurrentPage { get; set; }

        public int PageSize { get; set; }

        public int TotalPages { get; set; }

        public int StartPage { get; set; }

        public int EndPage { get; set; }

        public Pager()
        {

        }

        public Pager(int totalItems, int page, int pageSize = 10)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if(startPage <= 10)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }
            if(endPage > totalPages)
            {
                endPage = totalPages;
                if(endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;

        }
    }
}

WebsiteThietBiDienTu/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteThietBiDienTu.Data;
using WebsiteThietBiDienTu.Models;

namespace WebsiteThietBiDienTu.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }
        public void GetInfo()
        {
            ViewData["Sanpham"] = _context.Sanpham.Count();
            ViewData["Donhang"] = _context.Hoadon.Count();
            ViewData["Khachhang"] = _context.Khachhang.Count();
            ViewData["Doanhthu"] = _context.Hoadon.Sum(hd => hd.TongTien).ToString("n0").Replace(",", ".");
        }

        // GET: Admin
        public async Task<IActionResult> Index()
        {
            GetInfo();
            var applicationDbContext = _context.Nhanvien.Include(n => n.MaCvNavigation);
            return View(await applicationDbContext.ToListAsync());
        }

        private bool NhanvienExists(int id)
        {
            GetInfo();
            return _context.Nhanvien.Any(e => e.MaNv == id);
        }
        
        [HttpPost]
        public async Task<IActionResult> ThongKeHoaDon(DateTime Ngaybatdau, DateTime Ngayketthuc)
        {
            var lstHD = _context.Hoadon.Include(m => m.MaKhNavigation).Where(d => d.Ngay >= Ngaybatdau && d.Ngay <= Ngayketthuc && d.TrangThai.Equals("Đã giao hàng"));
            int tongtien = 0;
            foreach (Hoadon hd in lstHD)
            {
                tongtien += hd.TongTien;
            }
            ViewData["ngaybatdau"] = Ngaybatdau.Month.ToString() + "/" + Ngaybatdau.Day.ToString() + "/" + Ngaybatdau.Year.ToString();
            ViewData["ngayketthuc"] = Ngayketthuc.Month.ToString() + "/" + Ngayketthuc.Day.ToString() + "/" + Ngayketthuc.Year.ToString();
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstHD);
        }
        public async Task<IActionResult> ThongKe()
        {
            var applicationDbContext = _context.Hoadon.Include(h => h.MaDcNavigation).Include(h => h.MaKhNavigation);
            return View(await applicationDbContext.ToListAsync());
        }
    }
}

WebsiteThietBiDienTu/Controllers/HoadonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteThietBiDienTu.Data;
using WebsiteThietBiDienTu.Models;

namespace WebsiteThietBiDienTu.Controllers
{
    public class HoadonsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HoadonsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Hoadons
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Hoadon.Include(h => h.MaDcNavigation).Include(h => h.MaKhNavigation);
            return View(await applicationDbContext.ToListAsync());

        }

        // GET: Hoadons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon
                .Include(h => h.MaDcNavigation)
                .Include(h => h.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoadon == null)
            {
                return NotFound();
            }
            //ViewBag.cthd =await _context.Cthoadon.Where(cthd => cthd.MaHdNavigation.MaHd == id).Include(hd => hd.MaHdNavigation).Include(mh => mh.MaMhNavigation).Include(kh => kh.MaHdNavigation.MaKhNavigation).FirstOrDefaultAsync();
            ViewBag.cthd = await _context.Cthoadon
                            .Where(cthd => cthd.MaHdNavigation.MaHd == id)
                            .Include(hd => hd.MaHdNavigation)
                            .Include(mh => mh.MaMhNavigation)
                            .Include(kh => kh.MaHdNavigation.MaKhNavigation)
                            .ToListAsync();
            return View(hoadon);
        }

        // GET: Hoadons/Create
        public IActionResult Create()
        {
            ViewData["MaDc"] = new SelectList(_context.Set<Diachi>(), "MaDc", "DiaChi1");
            ViewData["MaKh"] = new SelectList(_context.Khachhang, "MaKh", "Ten");
            return View();
        }

        // POST: Hoadons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHd,Ngay,TongTien,MaKh,MaDc,TrangThai")] Hoadon hoadon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoadon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDc"] = new SelectList(_context.Set<Diachi>(), "MaDc", "DiaChi1", hoadon.MaDc);
            ViewData["MaKh"] = new SelectList(_context.Khachhang, "MaKh", "Ten", hoadon.MaKh);
            return View(hoadon);
        }

        // GET: Hoadons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon.FindAsync(id);
            if (hoadon == null)
            {
                return NotFound();
            }
            ViewData["MaDc"] = new SelectList(_context.Set<Diachi>(), "MaDc", "DiaChi1", hoadon.MaDc);
            ViewData["MaKh"] = new SelectList(_context.Khachhang, "MaKh", "Ten", hoadon.MaKh);
            return View(hoadon);
        }

        // POST: Hoadons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHd,Ngay,TongTien,MaKh,MaDc,TrangThai")] Hoadon hoadon)
        {
            if (id != hoadon.MaHd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoadon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoadonExists(hoadon.MaHd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDc"] = new SelectList(_context.Set<Diachi>(), "MaDc", "DiaChi1", hoadon.MaDc);
            ViewData["MaKh"] = new SelectList(_context.Khachhang, "MaKh", "Ten", hoadon.MaKh);
            return View(hoadon);
        }

        // GET: Hoadons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon
                .Include(h => h.MaDcNavigation)
                .Include(h => h.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // POST: Hoadons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoadon = await _context.Hoadon.FindAsync(id);
            _context.Hoadon.Remove(hoadon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoadonExists(int id)
        {
            return _context.Hoadon.Any(e => e.MaHd == id);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStatus(int id, string newStatus)
        {
            //1: cho xac nha
            //2: dang chuan bi hang
            //3: dang giao
            var order = _context.Hoadon.FirstOrDefault(o => o.MaHd == id);
            if (order != null)
            {
                order.TrangThai = newStatus;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

       

    }
}

WebsiteThietBiDienTu/Controllers/TintucsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteThietBiDienTu.Data;
using WebsiteThietBiDienTu.Models;

namespace WebsiteThietBiDienTu.Controllers
{
    public class TintucsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TintucsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tintucs
        public async Task<IActionResult> Index(string searchString)
        {
            return View(await _context.Tintuc.ToListAsync());
            //var data = from p in _context.Tintuc.FirstOrDefault(p => p.MaTin)
            //           select p;

            //if (!String.IsNullOrEmpty(searchString))
            //{
            //    data = data.Where(p => p.TieuDe.Contains(searchString));
            //}

            //return View(data);
        }

        // GET: Tintucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintuc
                .FirstOrDefaultAsync(m => m.MaTin == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // GET: Tintucs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tintucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaTin,TieuDe,TomTat,NoiDung,HinhAnh,NgayDang")] Tintuc tintuc, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                tintuc.HinhAnh = Upload(file);
                _context.Add(tintuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tintuc);
        }

        // GET: Tintucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintuc.FindAsync(id);
            if (tintuc == null)
            {
                return NotFound();
            }
            return View(tintuc);
        }

        // POST: Tintucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile file,[Bind("MaTin,TieuDe,TomTat,NoiDung,HinhAnh,NgayDang")] Tintuc tintuc)
        {
            if (id != tintuc.MaTin)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        tintuc.HinhAnh = Upload(file);
                    }
                    _context.Update(tintuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TintucExists(tintuc.MaTin))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tintuc);
        }

        // GET: Tintucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintuc
                .FirstOrDefaultAsync(m => m.MaTin == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // POST: Tintucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tintuc = await _context.Tintuc.FindAsync(id);
            _context.Tintuc.Remove(tintuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TintucExists(int id)
        {
            return _context.Tintuc.Any(e => e.MaTin == id);
        }

        public string Upload(IFormFile file)
        {
            string uploadFileName = null;
            if (file != null)
            {
                // phát sinh tên file mới: chuỗi ngẫu nhiên_tên ảnh
                uploadFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                // chép file về thư mục lưu trữ ảnh
                var path = $"wwwroot\\images\\news\\{uploadFileName}";
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

            }
            return uploadFileName; // trả về tên file
        }
    }
}

WebsiteThietBiDienTu/Views/Shared/_Carousel.cshtml
<section class="hero-slider">

    <div class="container-fluid">
        <div class="carousel slide shadow" data-bs-ride="carousel" data-interval="1000">
     
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
    </div>
    
    <div class="carousel-inner my-3">
        <div class="carousel-item active">

            <img src="/images/carousel/banner1.jpg" class="d-block w-100" height="300px">
        </div>
        <div class="carousel-item">
            <img src="/images/carousel/banner2.png" class="d-block w-100" height="300px">
        </div>
        <div class="carousel-item">
            <img src="/images/carousel/banner3.jpg" class="d-block w-100" height="300px">
        </div>
    </div>
     
    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                <span class="carousel-control-next-icon"></span>
            </button>
        </div>
    </div>
   
    
</section>

WebsiteThietBiDienTu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Tables</title>

    <!-- Custom fonts for this template -->
    <link href="/Admin_Page/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/Admin_Page/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="/Admin_Page/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

    

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon">
                    <img src="/images/carousel/logo.png" width="100%" height="100%" />
                </div>
                @*<div class="sidebar-brand-text mx-3"><img src="/images/carousel/logo.png" width="100%" height="100%"/></div>*@
            </a>


            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Admin">
                    <i class="fas fa-fw fa-table"></i>
                    <span>DashBoard</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Danhmucs">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Quản lý danh mục</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Sanphams">
                    <i class="fas fa-fw fa-table"></i>
                    <span> Quản lý sản phẩm</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Nhanviens">
                    <i class="fas fa-fw fa-table"></i>
                    <span> Quản lý nhân viên</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Khachhangs">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Quản lý khách hàng</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Hoadons">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Quản lý hóa đơn</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Tintucs">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Quản lý tin Tức</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="ThongKe" asp-controller="Admin">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Thống kê hóa đơn</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" asp-action="Logout" asp-controller="Home">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Đăng Xuất</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <form class="form-inline">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                    </form>

                    <!-- Topbar Search -->
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>




                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                @RenderBody()
                <!-- /.container-fluid -->
                
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Nguyễn Thị Cẩm Thu</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/Admin_Page/vendor/jquery/jquery.min.js"></script>
    <script src="/Admin_Page/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/Admin_Page/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/Admin_Page/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/Admin_Page/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/Admin_Page/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/Admin_Page/js/demo/datatables-demo.js"></script>

    @RenderSection("Scripts",required: false)
</body>

</html>

WebsiteThietBiDienTu/Views/Shared/_NotificationPartical.cshtml
@if (TempData["success"] != null)
{
    <div class="alert alert-success" id="notification">
        @TempData["success"]
    </div>
}
@if (TempData["error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["error"]
    </div>
}

<script>
    // Function to hide notifications after a certain time
    function hideNotifications() {
        setTimeout(function () {
            $('#notification').fadeOut('slow');
        }, 5000); // 5 seconds
    }

    // Call the function when the page is loaded
    $(document).ready(function () {
        hideNotifications();
    });
</script>

WebsiteThietBiDienTu/Views/Shared/_Pager.cshtml
@model WebsiteThietBiDienTu.Models.Pager;
@if (Model.TotalItems > 0)
    {
        <ul class="pagination justify-content-center" style="margin:20px 0">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Home" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Home"  asp-action="Index" asp-route-pg="@(Model.CurrentPage -1)">Previous</a>
                </li>
            }
            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge == Model.CurrentPage ? "active" :"")">
                    <a class="page-link" asp-controller="Home" asp-action="Index"  asp-route-pg="@pge">@pge</a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Home" asp-action="Index" asp-route-pg="@(Model.CurrentPage + 1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Home"  asp-action="Index" asp-route-pg="@(Model.TotalPages)">Last</a>
                </li>
            }
        </ul>
    }
<!-- Pagination -->