WebsiteThietBiDienTu/Models/Danhmuc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WebsiteThietBiDienTu.Models
{
    [Table("DANHMUC")]
    public partial class Danhmuc
    {
        public Danhmuc()
        {
            Sanpham = new HashSet<Sanpham>();
        }

        [Key]
        [Column("MaDM")]
        public int MaDm { get; set; }
        [Required]
        [StringLength(100)]
        public string Ten { get; set; }

        [InverseProperty("MaDmNavigation")]
        public virtual ICollection<Sanpham> Sanpham { get; set; }
    }
}

WebsiteThietBiDienTu/Controllers/DanhmucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteThietBiDienTu.Data;
using WebsiteThietBiDienTu.Models;

namespace WebsiteThietBiDienTu.Controllers
{
    public class DanhmucsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DanhmucsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Danhmucs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Danhmuc.ToListAsync());
        }

        // GET: Danhmucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmuc
                .FirstOrDefaultAsync(m => m.MaDm == id);
            if (danhmuc == null)
            {
                return NotFound();
            }

            return View(danhmuc);
        }

        // GET: Danhmucs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Danhmucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDm,Ten")] Danhmuc danhmuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhmuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(danhmuc);
        }

        // GET: Danhmucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmuc.FindAsync(id);
            if (danhmuc == null)
            {
                return NotFound();
            }
            return View(danhmuc);
        }

        // POST: Danhmucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaDm,Ten")] Danhmuc danhmuc)
        {
            if (id != danhmuc.MaDm)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhmuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhmucExists(danhmuc.MaDm))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(danhmuc);
        }

        // GET: Danhmucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmuc = await _context.Danhmuc
                .FirstOrDefaultAsync(m => m.MaDm == id);
            if (danhmuc == null)
            {
                return NotFound();
            }

            return View(danhmuc);
        }

        // POST: Danhmucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhmuc = await _context.Danhmuc.FindAsync(id);
            _context.Danhmuc.Remove(danhmuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DanhmucExists(int id)
        {
            return _context.Danhmuc.Any(e => e.MaDm == id);
        }
    }
}

WebsiteThietBiDienTu/Views/Danhmucs/Create.cshtml
@model WebsiteThietBiDienTu.Models.Danhmuc

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mx-auto">Thêm danh mục</h1>

<h4 class="mx-auto">Danh mục</h4>
<hr />
<div class="row mx-auto">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tên danh mục</label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mx-auto">
    <a asp-action="Index">Trở về trang chủ</a>
</div>

WebsiteThietBiDienTu/Views/Danhmucs/Delete.cshtml
@model WebsiteThietBiDienTu.Models.Danhmuc

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa danh mục</h1>

<h3>Bạn có muốn xóa danh mục này không?</h3>
<div>
    <h4 class="mx-auto">Danh mục</h4>
    <hr />
    <dl class="row mx-auto">
        <dt class = "col-sm-2">
            Tên danh mục
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
    </dl>
    
    <form asp-action="Delete" class="mx-auto">
        <input type="hidden" asp-for="MaDm" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Trở về trang chính</a>
    </form>
</div>

WebsiteThietBiDienTu/Views/Danhmucs/Details.cshtml
@model WebsiteThietBiDienTu.Models.Danhmuc

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mx-auto">Chi tiết danh mục</h1>

<div>
    <h4 class="mx-auto">Danh mục</h4>
    <hr />
    <dl class="row mx-auto">
        <dt class = "col-sm-2">
           Tên danh mục
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
    </dl>
</div>
<div class="mx-auto">
    <a class="btn btn-outline-warning mx-auto" asp-action="Edit" asp-route-id="@Model.MaDm">Chỉnh sửa</a> 
    <a class="btn btn-outline-primary" asp-action="Index">Trở về trang chủ</a>
</div>

WebsiteThietBiDienTu/Views/Danhmucs/Edit.cshtml
@model WebsiteThietBiDienTu.Models.Danhmuc

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mx-autto">Chỉnh sửa danh mục</h1>

<h4 class="mx-auto">Danh Mục</h4>
<hr />
<div class="row auto">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaDm" />
            <div class="form-group">
                <label class="control-label">Tên danh mục</label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mx-auto">
    <a class="btn btn-outline-primary" asp-action="Index">Trở lại trang chủ</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

WebsiteThietBiDienTu/Views/Danhmucs/Index.cshtml
@model IEnumerable<WebsiteThietBiDienTu.Models.Danhmuc>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">DANH MỤC</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DANH MỤC SẢN PHẨM</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">

                <table class="table table-bordered">
                    <a class="btn btn-outline-primary" asp-action="Create" asp-controller="Danhmucs">Thêm Danh Mục</a>
                    <thead>
                        <tr>
                            <th>Tên Danh Mục</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Ten)</td>                              
                                <td>
                                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.MaDm">Sửa</a>
                                    <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.MaDm">Chi Tiết</a>
                                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.MaDm">Xóa</a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>