WebsiteThietBiDienTu/Models/Sanpham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WebsiteThietBiDienTu.Models
{
    [Table("SANPHAM")]
    public partial class Sanpham
    {
        
        public Sanpham()
        {
            Cthoadon = new HashSet<Cthoadon>();
            Gopy = new HashSet<Gopy>();
        }

        [Key]
        [Column("MaMH")]
        public int MaMh { get; set; }
        [Required]
        [StringLength(100)]
        public string Ten { get; set; }
        public int GiaGoc { get; set; }
        public int GiaBan { get; set; }
        public short SoLuong { get; set; }
        [StringLength(1000)]
        public string MoTa { get; set; }
        [StringLength(255)]
        public string HinhAnh { get; set; }
        [Column("MaDM")]
        public int MaDm { get; set; }
        public int? LuotXem { get; set; }
        public int? LuotMua { get; set; }

        [ForeignKey(nameof(MaDm))]
        [InverseProperty(nameof(Danhmuc.Sanpham))]
        public virtual Danhmuc MaDmNavigation { get; set; }
        [InverseProperty("MaMhNavigation")]
        public virtual ICollection<Cthoadon> Cthoadon { get; set; }
        [InverseProperty("MaMhNavigation")]
        public virtual ICollection<Gopy> Gopy { get; set; }
    }
}

WebsiteThietBiDienTu/Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteThietBiDienTu.Data;
using WebsiteThietBiDienTu.Models;

namespace WebsiteThietBiDienTu.Controllers
{
    public class SanphamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SanphamsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sanphams
        public async Task<IActionResult> Index(int pg=1,string sortOrder="",string searchString="")
        {

          
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["GiaSortParm"] = sortOrder == "Gia" ? "gia_desc" : "Gia";
            ViewData["QuantitySortParm"] = sortOrder == "SoLuong" ? "soluong_desc" : "SoLuong";
            var data = from p in _context.Sanpham.Include(p => p.MaDmNavigation)
                       select p; 
            
            if (!String.IsNullOrEmpty(searchString))
            {
                data = data.Where(p => p.Ten.Contains(searchString));
            }
           
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(p => p.Ten);
                    break;
                case "Gia":
                    data = data.OrderBy(p => p.GiaBan);
                    break;
                case "gia_desc":
                    data = data.OrderByDescending(p => p.GiaBan);
                    break;
                case "SoLuong":
                    data = data.OrderBy(p => p.SoLuong);
                    break;
                case "soluong_desc":
                    data = data.OrderByDescending(p => p.SoLuong);
                    break;
                default:
                    data = data.OrderBy(p => p.Ten);
                    break;
            }

            return View(data);

        }

        // GET: Sanphams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham
                .Include(s => s.MaDmNavigation)
                .FirstOrDefaultAsync(m => m.MaMh == id);
            if (sanpham == null)
            {
                return NotFound();
            }

            return View(sanpham);
        }

        // GET: Sanphams/Create
        public IActionResult Create()
        {
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "Ten");
            return View();
        }

        // POST: Sanphams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaMh,Ten,GiaGoc,GiaBan,SoLuong,MoTa,HinhAnh,MaDm,LuotXem,LuotMua")] Sanpham sanpham, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                sanpham.HinhAnh = Upload(file);
                _context.Add(sanpham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "Ten", sanpham.MaDm);
            return View(sanpham);
        }

        // GET: Sanphams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham.FindAsync(id);
            if (sanpham == null)
            {
                return NotFound();
            }
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "Ten", sanpham.MaDm);
            return View(sanpham);
        }

        // POST: Sanphams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,IFormFile file, [Bind("MaMh,Ten,GiaGoc,GiaBan,SoLuong,MoTa,HinhAnh,MaDm,LuotXem,LuotMua")] Sanpham sanpham)
        {
            if (id != sanpham.MaMh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        sanpham.HinhAnh = Upload(file);
                    }
                    _context.Update(sanpham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanphamExists(sanpham.MaMh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDm"] = new SelectList(_context.Danhmuc, "MaDm", "Ten", sanpham.MaDm);
            return View(sanpham);
        }

        // GET: Sanphams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanpham = await _context.Sanpham
                .Include(s => s.MaDmNavigation)
                .FirstOrDefaultAsync(m => m.MaMh == id);
            if (sanpham == null)
            {
                return NotFound();
            }

            return View(sanpham);
        }

        // POST: Sanphams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanpham = await _context.Sanpham.FindAsync(id);
            _context.Sanpham.Remove(sanpham);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanphamExists(int id)
        {
            return _context.Sanpham.Any(e => e.MaMh == id);
        }
        public string Upload(IFormFile file)
        {
            string uploadFileName = null;
            if (file != null)
            {
                // phát sinh tên file mới: chuỗi ngẫu nhiên_tên ảnh
                uploadFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                // chép file về thư mục lưu trữ ảnh
                var path = $"wwwroot\\images\\products\\{uploadFileName}";
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

            }
            return uploadFileName; // trả về tên file
        }
    }
}

WebsiteThietBiDienTu/Views/Sanphams/Create.cshtml
@model WebsiteThietBiDienTu.Models.Sanpham

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/41.2.1/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('#txtMoTa'), {
            // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
        })
        .then(editor => {
            window.editor = editor;
        })
        .catch(err => {
            console.error(err.stack);
        });
</script>
<script>
    ClassicEditor
        .create(document.querySelector('#txtTen'), {
            // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
        })
        .then(editor => {
            window.editor = editor;
        })
        .catch(err => {
            console.error(err.stack);
        });
</script>
}
<h1>Create</h1>

<h4>Sanpham</h4>
<hr />
<div class="row mx-5">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tên sản phẩm</label>
                <textarea id="txtTen" asp-for="Ten" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giá gốc</label>
                <input asp-for="GiaGoc" class="form-control" />
                <span asp-validation-for="GiaGoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giá bán</label>
                <input asp-for="GiaBan" class="form-control" />
                <span asp-validation-for="GiaBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Số lượng</label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label class="control-label">Mô tả</label>
                    <input asp-for="MoTa" class="form-control" />
                    <span asp-validation-for="MoTa" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label class="control-label">Mô tả</label>
                <textarea id="txtMoTa" asp-for="MoTa" class="form-control" rows="5"></textarea>
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Hình ảnh</label>
                <input type="file" name="file" class="form-control" />
                <span asp-validation-for="HinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Danh mục</label>
                <select asp-for="MaDm" class="form-control" asp-items="ViewBag.MaDm"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Lượt xem</label>
                <input asp-for="LuotXem" class="form-control" />
                <span asp-validation-for="LuotXem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Lượt mua</label>
                <input asp-for="LuotMua" class="form-control" />
                <span asp-validation-for="LuotMua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mx-auto">
    <a asp-action="Index">Trở lại trang chủ</a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

WebsiteThietBiDienTu/Views/Sanphams/Delete.cshtml
@model WebsiteThietBiDienTu.Models.Sanpham

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xóa sản phẩm</h1>

<h3>Bạn có muốn xóa sản phẩm này không?</h3>
<div>
    <h4>Sanpham</h4>
    <hr />
    <dl class="row mx-auto">
        <dt class = "col-sm-2">
            Tên sản phẩm
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
           Giá gốc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>
        <dt class="col-sm-2">
            Giá bán
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaBan)
        </dd>
        <dt class = "col-sm-2">
           Số lượng
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class = "col-sm-2">
            Mô tả
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(Model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            Hình ảnh
        </dt>
        <dd class="col-sm-10">
            <img src="~/images/products/@Html.DisplayFor(model => model.HinhAnh)" class="img-thumbnail" width="100" />
        </dd>
        <dt class = "col-sm-2">
           Lượt xem
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotXem)
        </dd>
        <dt class = "col-sm-2">
           Lượt mua
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotMua)
        </dd>
        <dt class = "col-sm-2">
            Danh mục
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaDmNavigation.Ten)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaMh" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Trở về trang chủ</a>
    </form>
</div>

WebsiteThietBiDienTu/Views/Sanphams/Details.cshtml
@model WebsiteThietBiDienTu.Models.Sanpham

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Chi tiết sản phẩm</h1>

<div>
    <h4 class="mx-auto">Sản phẩm</h4>
    <hr />
    <dl class="row mx-auto">
        <dt class = "col-sm-2">
            Tên sản phẩm
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
           Giá gốc
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>
        <dt class="col-sm-2">
            Giá bán
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaBan)
        </dd>
        <dt class = "col-sm-2">
            Số lượng
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class = "col-sm-2">
            Mô tả
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(Model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            Hình ảnh
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/products/@Html.DisplayFor(model => model.HinhAnh)" class="img-thumbnail" width="100" />
        </dd>
        <dt class = "col-sm-2">
            Lượt xem
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotXem)
        </dd>
        <dt class = "col-sm-2">
           Lượt mua
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotMua)
        </dd>
        <dt class = "col-sm-2">
            Danh mục
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaDmNavigation.Ten)
        </dd>
    </dl>
</div>
<div class="mx-auto">
    <a asp-action="Edit" asp-route-id="@Model.MaMh">Chỉnh sửa</a> |
    <a asp-action="Index">Trang chủ</a>
</div>

WebsiteThietBiDienTu/Views/Sanphams/Edit.cshtml
@model WebsiteThietBiDienTu.Models.Sanpham

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script src="https://cdn.ckeditor.com/ckeditor5/41.2.1/classic/ckeditor.js"></script>
    <script>
    ClassicEditor
        .create(document.querySelector('#txtMoTa'), {
            // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
        })
        .then(editor => {
            window.editor = editor;
        })
        .catch(err => {
            console.error(err.stack);
        });
    </script>
    <script>
        ClassicEditor
            .create(document.querySelector('#txtTen'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}
<h1>Chỉnh sửa</h1>

<h4>Sanpham</h4>
<hr />
<div class="row mx-auto">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaMh" />
            <div class="form-group">
                <label class="control-label">Tên sản phẩm</label>
                <textarea id="txtTen" asp-for="Ten" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giá gốc</label>
                <input asp-for="GiaGoc" class="form-control" />
                <span asp-validation-for="GiaGoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giá bán</label>
                <input asp-for="GiaBan" class="form-control" />
                <span asp-validation-for="GiaBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Số lượng</label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mô tả</label>
                <textarea id="txtMoTa" asp-for="MoTa" class="form-control" rows="4"></textarea>
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Hình ảnh</label>
                <img width="100" class="img-thumbnail" src="~/images/products/@Html.DisplayFor(model => model.HinhAnh)" />
                <input type="hidden" asp-for="HinhAnh" class="form-control" />
                <input type="file" name="file" />
                <span asp-validation-for="HinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Danh mục</label>
                <select asp-for="MaDm" class="form-control" asp-items="ViewBag.MaDm"></select>
                <span asp-validation-for="MaDm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Lượt xem</label>
                <input asp-for="LuotXem" class="form-control" />
                <span asp-validation-for="LuotXem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Lượt mua</label>
                <input asp-for="LuotMua" class="form-control" />
                <span asp-validation-for="LuotMua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mx-auto">
    <a asp-action="Index">Back to List</a>
</div>

WebsiteThietBiDienTu/Views/Sanphams/Index.cshtml
@model IEnumerable<WebsiteThietBiDienTu.Models.Sanpham>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

}

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Sản phẩm</h1>
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">TÁT CẢ SẢN PHẨM</h6>
            </div>
            <div class="card-body">
                <form class="py-auto mx-auto" asp-action="Index" method="get">
                    <input type="text" name="searchString" placeholder="Từ khóa tìm kiếm">
                    <button type="submit" class="btn btn-outline-primary">Tìm kiếm</button> |
                    <a asp-action="Index">Xóa tìm kiếm</a>
                </form>
                <div class="table-responsive">

                    <table class="table table-bordered">
                        <a class="btn btn-outline-primary" asp-action="Create" asp-controller="Sanphams">Thêm Sản Phẩm</a>

                        <thead>
                            <tr>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">Tên</a>
                                </th>
                                <th>
                                    Giá Gốc
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">Giá Ban</a>
                                </th>
                                <th>
                                    <a asp-action="Index" asp-route-sortOrder="@ViewData["QuantitySortParm"]">Số lượng</a>
                                </th>
                                <th>
                                    Mô Tả
                                </th>
                                <th>
                                    Hình ảnh
                                </th>
                                <th>
                                    Lượt Xem
                                </th>
                                <th>
                                    Lượt Mua
                                </th>
                                <th>
                                    Tên Danh mục
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.Raw(item.Ten)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GiaGoc)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GiaBan)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SoLuong)
                                    </td>
                                    <td>
                                        @Html.Raw(item.MoTa)
                                    </td>
                                    <td>
                                        <img src="~/images/products/@Html.DisplayFor(modelItem => item.HinhAnh)" class="img-thumbnail" width="100" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LuotXem)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LuotMua)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MaDmNavigation.Ten)
                                    </td>
                                    <td>
                                        <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.MaMh">Sửa</a>
                                        <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.MaMh">Chi Tiết</a>
                                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.MaMh">Xóa</a>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>

    <!-- DataTales Example -->


</div>
@*<div class="container">

        @if (pager.TotalItems > 1)
        {
            <ul class="pagination justify-content-center" style="margin:20px 0">
                @if (pager.CurrentPage >= 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Sanphams" asp-action="Index" asp-route-pg="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Sanphams" asp-action="Index" asp-route-pg="@(pager.CurrentPage -1)">Previous</a>
                    </li>
                }
                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" :"")">
                        <a class="page-link"  asp-controller="Sanphams" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </li>
                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Sanphams" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Sanphams" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </div>*@